from __future__ import annotations

from pathlib import Path


DISCOVERY_FILES = {
    "organization-profile.yaml": """organization:\n  name: {name}\n  type: \"\"\n  industry: \"\"\n  size: \"\"\n  geography: []\n  business_model: \"\"\n  products_services: []\n  customers_users: []\n\noperating_model:\n  critical_processes: []\n  decision_makers: []\n  service_levels: []\n  bottlenecks: []\n  recurrent_manual_checks: []\n  recurrent_exceptions: []\n\ntechnology:\n  systems: []\n  integrations: []\n  deployment_constraints: []\n  security_constraints: []\n  data_residency: []\n\nopportunities:\n  pains: []\n  late_decisions: []\n  reactive_processes: []\n  candidate_use_cases: []\n\nconstraints:\n  regulatory: []\n  privacy: []\n  destructive_actions: []\n  human_approval_required: []\n\nunknowns: []\n""",
    "DISCOVERY-WORKSHEET.md": """# Discovery Worksheet — {name}\n\n## Business\n- Business model:\n- Customers/users:\n- Critical value streams:\n\n## Operations\n- Critical processes:\n- Queues/handoffs:\n- Bottlenecks/rework:\n- Recurrent exceptions:\n\n## Decisions\n- Which decision should happen earlier?\n- Who owns it?\n- What action is available?\n- What is the cost of delay/error?\n\n## Data\n- Systems of Record:\n- Files/APIs/events:\n- Semantic unknowns:\n\n## Technology\n- Deployment constraints:\n- Security constraints:\n- Integration mechanisms:\n\n## Governance\n- Human approval boundaries:\n- Regulatory/privacy constraints:\n- Audit requirements:\n\n## Candidate first vertical slice\n- TBD\n""",
    "DATA-INVENTORY.md": """# Data Inventory — {name}\n\n| Source | Class | Owner | Authority | Access | Grain | Keys | Time fields | Freshness | Unknowns |\n|---|---|---|---|---|---|---|---|---|---|\n\n## Reconciliation references\n- TBD\n\n## Semantic risks\n- TBD\n""",
    "SOLUTION-ARCHETYPE.md": """# Solution Archetype — {name}\n\nPrimary archetype: `{archetype}`\n\nValidate this hypothesis during discovery. Candidate archetypes include exception-management, predictive-operations, constraint-coverage, asset-condition, customer-account, workflow-process, commercial-revenue, risk-compliance, capacity-resource and strategic-intelligence.\n\n## Decision owner\n- TBD\n\n## First decision to improve\n- TBD\n\n## Candidate patterns\n- TBD\n""",
    "domain-pack.draft.yaml": """id: {slug}\nname: {name}\nversion: 0.1.0\ndescription: Discovery-stage Domain Pack generated by Pyrax bootstrap.\nproblem:\n  decision_to_improve: TBD\n  decision_owner: TBD\n  allowed_actions: [review]\nsources: []\nentities: []\nrelationships: []\noperational_grain: TBD\nstates: []\ntimestamps: []\nsemantics:\n  certified: []\n  candidates: []\n  unknowns: [discovery-incomplete]\nsignals: []\ndecisions: []\nevidence:\n  required: true\n  fields: [source, grain, observed_at, rule_version, confidence]\nconfidence:\n  vocabulary: [CERTIFIED, ASSISTED, INSUFFICIENT_DATA]\napproval_policy:\n  mode: HUMAN_ASSISTED\noutcomes: []\nguardrails:\n  - UNKNOWN must not be converted to zero\nimplementation:\n  technology_profile: not-selected\n  golden_cases: false\n  contract_tests: false\n  reconciliation_tests: false\n  runtime: false\n  integration_tests: false\n  deployment: false\nux:\n  primary_user: TBD\n  primary_question: TBD\n  primary_action: TBD\n""",
    "NEXT-STEPS.md": """# Next Steps — {name}\n\n1. Complete `organization-profile.yaml`.\n2. Run interviews/workshops using `DISCOVERY-WORKSHEET.md`.\n3. Populate `DATA-INVENTORY.md`.\n4. Validate or change the proposed solution archetype.\n5. Select one decision-support vertical.\n6. Replace placeholders in `domain-pack.draft.yaml` with observed facts.\n7. Rename it to `domain-pack.yaml` only when the structure is ready for validation.\n8. Run `pyrax validate domain-pack.yaml`.\n9. Run `pyrax assess domain-pack.yaml`.\n10. Run `pyrax scaffold <solution-name> --domain-pack domain-pack.yaml`.\n""",
}


def _slug(value: str) -> str:
    return "-".join(part for part in value.lower().replace("_", "-").split() if part) or "new-organization"


def bootstrap_discovery(
    name: str,
    destination: str | Path,
    *,
    archetype: str = "to-be-discovered",
    force: bool = False,
) -> Path:
    root = Path(destination) / f"{_slug(name)}-discovery"
    if root.exists() and any(root.iterdir()) and not force:
        raise FileExistsError(f"Destination is not empty: {root}")
    root.mkdir(parents=True, exist_ok=True)
    context = {"name": name, "slug": _slug(name), "archetype": archetype}
    for relative, content in DISCOVERY_FILES.items():
        target = root / relative
        if target.exists() and not force:
            continue
        target.write_text(content.format(**context), encoding="utf-8")
    return root
