from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

from pyrax.catalogs import get_solution_profile
from pyrax.composition import materialize_solution_manifest


FILES = {
    "README.md": "# {name}\n\nGenerated from Pyrax Framework.\n\nSolution profile: `{solution_profile}`.\n\nStart with `domain-pack.yaml` and `solution-manifest.yaml`, then implement the smallest evidence-backed vertical slice.\n",
    "AGENTS.md": "# AGENTS.md — {name}\n\n## Rule\n\nPreserve domain truth, explicit UNKNOWN states, Evidence, granular confidence and human approval defaults.\n\n## Build order\n\n`Source -> Semantics -> Contract -> Quality -> Reconciliation -> State -> Signal -> Decision -> Evidence -> UX`\n\nDo not move product-specific semantics into the generic Pyrax runtime.\n",
    "docs/PRODUCT-CHARTER.md": "# Product Charter — {name}\n\n## Problema\n{problem}\n\n## Decisão a melhorar\n{decision}\n\n## Decision owner\n{owner}\n\n## Ações permitidas\n{actions}\n",
    "docs/ARCHITECTURE.md": "# Architecture — {name}\n\nTechnology profile: `{technology_profile}`\nSolution profile: `{solution_profile}`\n\nCanonical flow:\n\n`Sources -> Adapters -> Contracts -> Quality -> Reconciliation -> Operational State -> Signals -> Decision Support -> Evidence -> UX -> Outcome`\n\nThe final architecture must be adapted to domain, security and deployment constraints.\n",
    "docs/SOURCE-MAP.md": "# Source Map — {name}\n\n{sources}\n",
    "docs/SIGNAL-CATALOG.md": "# Signal Catalog — {name}\n\n{signals}\n",
    "docs/DECISION-CATALOG.md": "# Decision Catalog — {name}\n\n{decisions}\n",
    "docs/COMPOSITION.md": "# Solution Composition — {name}\n\n## Profile\n`{solution_profile}`\n\n## Building blocks\n{blocks}\n\n## Adapters\n{adapters}\n\n## UI components\n{ui_components}\n\nThese are reusable mechanics and presentation contracts. Domain semantics still require local validation.\n",
    "docs/EVIDENCE-CONTRACT.md": "# Evidence Contract — {name}\n\nEvery published decision-support output must preserve source, grain, cutoff/observation time, rule version, quality, confidence and lineage when applicable.\n",
    "docs/QA-PLAN.md": "# QA Plan — {name}\n\n## Golden Cases\n\n## Contract tests\n\n## Reconciliation\n\n## Integration tests\n\n## Failure modes\n\n## Deployment smoke\n",
    "golden-cases/README.md": "# Golden Cases\n\nDeterministic reference scenarios for regression. Never rewrite expected outcomes merely to make new code pass.\n",
    "src/{package}/__init__.py": "\"\"\"{name} domain package generated by Pyrax Framework.\"\"\"\n",
    "src/{package}/domain.py": "\"\"\"Domain-specific contracts and rules belong here, not in generic Pyrax runtime.\"\"\"\n",
    "src/{package}/adapters.py": "\"\"\"Product-specific source adapters implement Pyrax source ports here.\"\"\"\n",
    "src/{package}/composition.py": "\"\"\"Bind selected Pyrax building blocks to certified domain semantics here.\"\"\"\n",
    "tests/README.md": "# Tests\n\nAdd Golden Case, contract, reconciliation and integration coverage before promoting readiness.\n",
    "config/.gitkeep": "",
}


def _package_name(name: str) -> str:
    normalized = re.sub(r"[^a-zA-Z0-9]+", "_", name).strip("_").lower()
    return normalized or "pyrax_solution"


def _list_lines(values: list[str]) -> str:
    return "\n".join(f"- {value}" for value in values) or "- TBD"


def _source_table(pack: dict) -> str:
    lines = ["| Fonte | Autoridade | Acesso | Grão | Freshness |", "|---|---|---|---|---|"]
    for source in pack.get("sources", []):
        lines.append(
            f"| {source.get('system', source.get('id', ''))} | {source.get('authority', '')} | "
            f"{source.get('access_mode', '')} | {source.get('grain', '')} | {source.get('freshness', '') or ''} |"
        )
    return "\n".join(lines)


def _signal_table(pack: dict) -> str:
    lines = ["| Signal | Regra | Evidência |", "|---|---|---|"]
    for signal in pack.get("signals", []):
        evidence = ", ".join(signal.get("evidence_required", []))
        lines.append(f"| {signal.get('id', '')} | {signal.get('rule', '')} | {evidence} |")
    return "\n".join(lines)


def _decision_table(pack: dict) -> str:
    lines = ["| Decision | Trigger | Recommendation | Human approval |", "|---|---|---|---|"]
    for decision in pack.get("decisions", []):
        triggers = ", ".join(decision.get("triggered_by", []))
        lines.append(
            f"| {decision.get('id', '')} | {triggers} | {decision.get('recommendation', '')} | "
            f"{decision.get('human_approval_required', True)} |"
        )
    return "\n".join(lines)


def scaffold_project(
    name: str,
    destination: str | Path,
    *,
    domain_pack: dict | None = None,
    solution_profile: str | None = None,
    solution_manifest: dict | None = None,
    force: bool = False,
) -> Path:
    pack = domain_pack or {}
    if solution_manifest:
        composition = materialize_solution_manifest(solution_manifest)
    elif solution_profile:
        profile = get_solution_profile(solution_profile)
        composition = {
            "profile": solution_profile,
            "description": profile.get("description", ""),
            "blocks": profile.get("blocks", []),
            "adapters": profile.get("adapters", []),
            "ui_components": profile.get("ui_components", []),
            "maturity_target": profile.get("maturity_target"),
            "technology_profile": "not-selected",
        }
    else:
        composition = {
            "profile": "custom",
            "description": "Custom Pyrax composition",
            "blocks": [],
            "adapters": [],
            "ui_components": [],
            "maturity_target": None,
            "technology_profile": "not-selected",
        }

    display_name = pack.get("name") or name
    problem = pack.get("problem", {})
    implementation = pack.get("implementation", {})
    technology_profile = composition.get("technology_profile")
    if technology_profile in {None, "not-selected"}:
        technology_profile = implementation.get("technology_profile", "not-selected")
    context = {
        "name": display_name,
        "package": _package_name(name),
        "problem": problem.get("statement") or problem.get("decision_to_improve", "TBD"),
        "decision": problem.get("decision_to_improve", "TBD"),
        "owner": problem.get("decision_owner", "TBD"),
        "actions": _list_lines(problem.get("allowed_actions", [])),
        "sources": _source_table(pack),
        "signals": _signal_table(pack),
        "decisions": _decision_table(pack),
        "technology_profile": technology_profile,
        "solution_profile": composition.get("profile", "custom"),
        "blocks": _list_lines(composition.get("blocks", [])),
        "adapters": _list_lines(composition.get("adapters", [])),
        "ui_components": _list_lines(composition.get("ui_components", [])),
    }

    root = Path(destination) / name
    if root.exists() and any(root.iterdir()) and not force:
        raise FileExistsError(f"Destination is not empty: {root}")
    root.mkdir(parents=True, exist_ok=True)

    for relative, content in FILES.items():
        target = root / relative.format(**context)
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.exists() and not force:
            continue
        target.write_text(content.format(**context), encoding="utf-8")

    if pack:
        (root / "domain-pack.yaml").write_text(
            yaml.safe_dump(pack, sort_keys=False, allow_unicode=True), encoding="utf-8"
        )
        (root / "domain-pack.json").write_text(
            json.dumps(pack, ensure_ascii=False, indent=2), encoding="utf-8"
        )
    (root / "solution-manifest.yaml").write_text(
        yaml.safe_dump(composition, sort_keys=False, allow_unicode=True), encoding="utf-8"
    )
    return root
