from __future__ import annotations

import json
import re
from pathlib import Path

import yaml


FILES = {
    "README.md": "# {name}\n\nGenerated from Pyrax Framework.\n",
    "docs/PRODUCT-CHARTER.md": "# Product Charter — {name}\n\n## Problema\n{problem}\n\n## Decisão a melhorar\n{decision}\n\n## Decision owner\n{owner}\n\n## Ações permitidas\n{actions}\n",
    "docs/SOURCE-MAP.md": "# Source Map — {name}\n\n{sources}\n",
    "docs/SIGNAL-CATALOG.md": "# Signal Catalog — {name}\n\n{signals}\n",
    "docs/DECISION-CATALOG.md": "# Decision Catalog — {name}\n\n{decisions}\n",
    "docs/QA-PLAN.md": "# QA Plan — {name}\n\n## Golden Cases\n\n## Contract tests\n\n## Reconciliation\n\n## Failure modes\n",
    "golden-cases/README.md": "# Golden Cases\n\nDeterministic reference scenarios for regression.\n",
    "src/{package}/__init__.py": "\"\"\"{name} domain package generated by Pyrax Framework.\"\"\"\n",
    "tests/.gitkeep": "",
    "config/.gitkeep": "",
}


def _package_name(name: str) -> str:
    normalized = re.sub(r"[^a-zA-Z0-9]+", "_", name).strip("_").lower()
    return normalized or "pyrax_solution"


def _list_lines(values: list[str]) -> str:
    return "\n".join(f"- {value}" for value in values) or "- TBD"


def _source_table(pack: dict) -> str:
    lines = ["| Fonte | Autoridade | Acesso | Grão | Freshness |", "|---|---|---|---|---|"]
    for source in pack.get("sources", []):
        lines.append(
            f"| {source.get('system', source.get('id', ''))} | {source.get('authority', '')} | "
            f"{source.get('access_mode', '')} | {source.get('grain', '')} | {source.get('freshness', '') or ''} |"
        )
    return "\n".join(lines)


def _signal_table(pack: dict) -> str:
    lines = ["| Signal | Regra | Evidência |", "|---|---|---|"]
    for signal in pack.get("signals", []):
        evidence = ", ".join(signal.get("evidence_required", []))
        lines.append(f"| {signal.get('id', '')} | {signal.get('rule', '')} | {evidence} |")
    return "\n".join(lines)


def _decision_table(pack: dict) -> str:
    lines = ["| Decision | Trigger | Recommendation | Human approval |", "|---|---|---|---|"]
    for decision in pack.get("decisions", []):
        triggers = ", ".join(decision.get("triggered_by", []))
        lines.append(
            f"| {decision.get('id', '')} | {triggers} | {decision.get('recommendation', '')} | "
            f"{decision.get('human_approval_required', True)} |"
        )
    return "\n".join(lines)


def scaffold_project(
    name: str,
    destination: str | Path,
    *,
    domain_pack: dict | None = None,
    force: bool = False,
) -> Path:
    pack = domain_pack or {}
    display_name = pack.get("name") or name
    problem = pack.get("problem", {})
    context = {
        "name": display_name,
        "package": _package_name(name),
        "problem": problem.get("statement") or problem.get("decision_to_improve", "TBD"),
        "decision": problem.get("decision_to_improve", "TBD"),
        "owner": problem.get("decision_owner", "TBD"),
        "actions": _list_lines(problem.get("allowed_actions", [])),
        "sources": _source_table(pack),
        "signals": _signal_table(pack),
        "decisions": _decision_table(pack),
    }

    root = Path(destination) / name
    if root.exists() and any(root.iterdir()) and not force:
        raise FileExistsError(f"Destination is not empty: {root}")
    root.mkdir(parents=True, exist_ok=True)

    for relative, content in FILES.items():
        target = root / relative.format(**context)
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.exists() and not force:
            continue
        target.write_text(content.format(**context), encoding="utf-8")

    if pack:
        (root / "domain-pack.yaml").write_text(
            yaml.safe_dump(pack, sort_keys=False, allow_unicode=True), encoding="utf-8"
        )
        (root / "domain-pack.json").write_text(
            json.dumps(pack, ensure_ascii=False, indent=2), encoding="utf-8"
        )
    return root
